  version: "3"
  services:
    web:
      container_name: web
      build:
        context: .
        dockerfile: Dockerfile-web
      environment:
        - ALLOW_OVERRIDE=true
      ports:
        - "80:80"
      volumes:
        - ./src/web:/var/www/html
      depends_on:
        sgbd:
          condition: service_healthy
      networks:
        - frontend
        - backend
    sgbd:
      container_name: sgbd
      build:
        context: .
        dockerfile: Dockerfile-sgbd
      ports:
        - "5432:5432"
      volumes:
        - sgbd-data:/var/lib/postgresql/data
      networks:
        - backend
    robot:
      container_name: robot
      build:
        context: .
        dockerfile: Dockerfile-robot
      depends_on:
        sgbd:
          condition: service_healthy
      networks:
        - backend
    sabd:
      container_name: sabd
      image: adminer:latest
      ports:
        - "8080:8080"
      depends_on:
        sgbd:
          condition: service_healthy
      networks:
        - backend
    vault:
      container_name: vault
      build:
        context: .
        dockerfile: Dockerfile-vault
      ports:
        - "8200:8200"
      networks:
        - backend
  volumes:
    sgbd-data:
  networks:
    frontend:
    backend:
