FROM hashicorp/vault:latest

ENV VAULT_ADDR=http://127.0.0.1:8200

# Copiar el fichero de configuración de Vault
COPY ./src/vault/config/ /vault/config/

# Script de configuración de Vault
COPY ./src/vault/script/entrypoint.sh /usr/local/bin/entrypoint.sh

# Dar permisos de ejecución al script
RUN chmod +x /usr/local/bin/entrypoint.sh

COPY ./src/vault/file/ /vault/file/

# CMD: Comando para iniciar Vault con configuración personalizada
CMD ["/usr/local/bin/entrypoint.sh"]