  version: "3"
  services:
    web:
      container_name: web
      build:
        context: .
        dockerfile: Dockerfile-web
      environment:
        - ALLOW_OVERRIDE=true
      ports:
        - "80:80"
      volumes:
        - ./src/web:/var/www/html
      links:
        - sabd
      depends_on:
        - sabd
    sgbd:
      container_name: sgbd
      build:
        context: .
        dockerfile: Dockerfile-sgbd
      ports:
        - "5432:5432"
      volumes:
        - sgbd-data:/var/lib/postgresql/data
    sabd:
      container_name: sabd
      image: adminer:latest
      ports:
        - "8080:8080"
      depends_on:
        - sgbd
      links: 
        - sgbd
    robot:
      container_name: robot
      build:
        context: .
        dockerfile: Dockerfile-robot
      depends_on:
        - sgbd
      links:
        - sgbd
    vault:
      container_name: vault
      build:
        context: .
        dockerfile: Dockerfile-vault
      ports:
        - "8200:8200"
        - "8201:8201"
      volumes:
        - ./src/vault:/vault/file
  volumes:
    sgbd-data:
