  version: "3"
  services:
    web:
      container_name: web
      build:
        context: .
        dockerfile: Dockerfile-web
      environment:
        - ALLOW_OVERRIDE=true
      ports:
        - "80:80"
      volumes:
        - ../src/web:/var/www/html
      links:
        - adminer
      depends_on:
        - adminer
    
    bbdd:
      container_name: postgres
      image: postgres:latest
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: db
      volumes:
        - ../src/db/data:/var/lib/postgresql/data

    adminer:
      container_name: adminer
      image: adminer:latest
      ports:
        - "8080:8080"