FROM postgres:latest

# Variables de entorno
ENV POSTGRES_PASSWORD=1234
ENV POSTGRES_DB=db
ENV POSTGRES_USER=xabier
ENV POSTGRES_HOST_AUTH_METHOD=trust

# Copiar la base de datos a la carpeta de inicialización
COPY ./src/db/db.sql /docker-entrypoint-initdb.d/