FROM python:slim

RUN apt-get update -y && apt-get install -y python3 python3-pip

RUN python3 -m pip install --upgrade pip

WORKDIR /app

COPY ./src/robot/* .

RUN pip install -r requirements.txt

CMD ["python3", "robot.py"]
