apiVersion: v1
kind: PersistentVolume
metadata:
  name: sgbd-volume
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  hostPath:
    path: ..\Docker\src\db\data
  accessModes:
    - ReadWriteOnce