apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-volume
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  hostPath:
    path: ..\Docker\src\vault
  accessModes:
    - ReadWriteOnce