apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-d
  template:
    metadata:
      labels:
        app: vault-d
    spec:
      containers:
      - name: vault-p
        image: xabierland/vault:latest
        ports:
        - containerPort: 8200