apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-volume
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  hostPath:
    path: ..\Docker\src\web
  accessModes:
    - ReadWriteOnce